apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: student-<NUMBER>-jenkins
  namespace: argocd
spec:
  project: default
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: student-12
  syncPolicy:
    automated: {}
  sources:
    - repoURL: 'https://charts.bitnami.com/bitnami'
      targetRevision: 12.4.0
      helm:
        valueFiles:
          - $values/jenkins/values.yaml
      chart: jenkins
    - repoURL: 'https://github.com/PerTerkelsen/argocd-katas-training'
      targetRevision: main
      ref: values
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: student-<NUMBER>
  syncPolicy:
    automated:
      prune: true
      selfHeal: true